### ISSUE TITLE
Add link in "About" section of github

### ISSUE THREAD

**Issue by tomassalina** [carosalazar28/personalPortfolio#1]
Hola! he visto tu portafolio y algo que te ayudaría mucho es que los usuarios puedan entrar directamente a ver tus proyectos, y no tener que clonar el repositorio o algo parecido. Una forma de lograrlo es poner un link en la sección de GitHub "ABOUT" o en el README.md.
![](https://i.imgur.com/8VNVjx6.png)
Esto, además de ser una buena práctica, lograría que la gente pueda ver las cosas increíbles que haces de forma mucho más fácil y cómoda
Espero te sirva!

**Comment by carosalazar28** [comment]
Muchas gracias Tomas por tu feedback, ya me estoy encargando de hacer esto.
